name: doc
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust for WASM
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: compile the plugin
        run: cargo build

      - name: copy the plugin in the typst folder
        run: cp target/wasm32-unknown-unknown/debug/typst_vhdl_parse.wasm typst

      - name: generate the documentation
        run: mkdir typst/doc/page; typst compile --root . typst/doc/doc.typ typst/doc/page/doc.pdf

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: typst/doc/page

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
